#!/bin/sh

# set -e : Exit the script if any statement returns a non-true return value.
# set -o pipefail : Check the exit code of pipeline's last command.
# set -u : Exit the script when using uninitialised variable.
set -euo pipefail

# Reset PATH to avoid messed up duplication
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

## Define default variables to be used in the config file
export PHP_FPM_PM=${PHP_FPM_PM:='ondemand'}
export PHP_FPM_PM_MAX_CHILDREN=${PHP_FPM_PM_MAX_CHILDREN:='9'}
export PHP_FPM_PM_PROCESS_IDLE_TIMEOUT=${PHP_FPM_PM_PROCESS_IDLE_TIMEOUT:='10s'}
export PHP_FPM_PM_MAX_REQUEST=${PHP_FPM_PM_MAX_REQUEST:='200'}
export PHP_FPM_PM_START_SERVER=${PHP_FPM_PM_START_SERVER:='2'}
export PHP_FPM_PM_MIN_SPARE_SERVERS=${PHP_FPM_PM_MIN_SPARE_SERVERS:='1'}
export PHP_FPM_PM_MAX_SPARE_SERVERS=${PHP_FPM_PM_MAX_SPARE_SERVERS:='3'}
export PHP_FPM_PM_CLEAR_ENV=${PHP_FPM_PM_CLEAR_ENV:='no'}
export PHP_FPM_PM_CATCH_WORKERS_OUTPUT=${PHP_FPM_PM_CATCH_WORKERS_OUTPUT:='yes'}

# Create php-fpm.d directory
mkdir -p "/etc/php7/php-fpm.d/"
chown -R www-data:www-data "/etc/php7/php-fpm.d/"

# Use templater to generate config files
templater /etc/entrypoint.d/php-fpm.cnf/www.conf.tpl > /etc/php7/php-fpm.d/www.conf
