FROM dsuite/alpine-runit:3.9

LABEL maintainer="Hexosse <hexosse@gmail.com>" \
      description="Minimal Alpine image with php7 and runit process supervisor." \
      vendor="docker-suite" \
      license="MIT"


## Current php version
ENV PHP_VERSION=7.2


## When using Composer, disable the warning about running commands as root/super user
ENV COMPOSER_ALLOW_SUPERUSER=1


## php packages
COPY --from=dsuite/php-repo:all /repo /tmp/repo
COPY --from=dsuite/php-repo:all /etc/apk/keys /etc/apk/keys


## Add Trust key for php packages.
ADD https://repos.php.earth/alpine/phpearth.rsa.pub /etc/apk/keys/phpearth.rsa.pub


## Install
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk-update \
    # Add packages
    && apk-install --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ \
        ca-certificates \
        libcap \
        memcached \
        openssh-client \
        tar \
        zip \
        wget \
        # https://github.com/docker-library/php/issues/494
        libressl


## Install php
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk-update \
    # Add packages
    && apk-install --repository /tmp/repo/3.9/php \
        php7.2 \
        php7.2-fpm \
        # php libs
        php7.2-apcu \
        php7.2-bcmath \
        php7.2-common \
        php7.2-ctype \
        php7.2-curl \
        php7.2-dom \
        php7.2-fileinfo \
        php7.2-gd \
        php7.2-iconv \
        php7.2-json \
        php7.2-mbstring \
        php7.2-memcached \
        php7.2-mysqli \
        php7.2-opcache \
        php7.2-openssl \
        php7.2-pdo \
        php7.2-pdo_mysql \
        php7.2-pgsql \
        php7.2-pdo_sqlite \
        php7.2-phar \
        php7.2-redis \
        php7.2-session \
        php7.2-simplexml \
        php7.2-sqlite3 \
        php7.2-tokenizer \
        php7.2-xml \
        php7.2-xmlreader \
        php7.2-xmlwriter \
        php7.2-zip \
        php7.2-zlib \
        # Composer
        composer \
        php7.2-composer \
	# Clear apk's cache
	&& apk-cleanup


## Copy scripts
ADD /rootfs /


## Config
RUN \
    ln -s "/etc/php/$PHP_VERSION/" "/etc/php7" \
    && rm -f "/etc/php7/php-fpm.conf" \
    && ln -s "/etc/php/php-fpm.conf" "/etc/php7/php-fpm.conf" \
    # Create default webroot folder
    && mkdir -p /var/www \
    && chown www-data:www-data /var/www


## Expose php-fpm port
EXPOSE 9000
