FROM dsuite/alpine-php:{{DSUITE_VERSION}}


# LABEL org.opencontainers.image.title="docker-suite dsuite/alpine-php:{{PHP_VERSION}}-cli image" \
#     org.opencontainers.image.created="{{DOCKER_IMAGE_CREATED}}" \
#     org.opencontainers.image.revision="{{DOCKER_IMAGE_REVISION}}"


CMD ["php"]
