FROM dsuite/alpine-runit:3.9

LABEL maintainer="Hexosse <hexosse@gmail.com>" \
      description="Minimal Alpine image with php7 and runit process supervisor." \
      vendor="docker-suite" \
      license="MIT"


## Current php version
ENV PHP_VERSION=7.1


## When using Composer, disable the warning about running commands as root/super user
ENV COMPOSER_ALLOW_SUPERUSER=1


## php packages
COPY --from=dsuite/php-repo:all /repo /tmp/repo
COPY --from=dsuite/php-repo:all /etc/apk/keys /etc/apk/keys


## Add Trust key for php packages.
ADD https://repos.php.earth/alpine/phpearth.rsa.pub /etc/apk/keys/phpearth.rsa.pub


## Install
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk-update \
    # Add packages
    && apk-install --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ \
        ca-certificates \
        libcap \
        memcached \
        openssh-client \
        tar \
        zip \
        wget \
        # https://github.com/docker-library/php/issues/494
        libressl


## Install php
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk-update \
    # Add packages
    && apk-install --repository /tmp/repo/3.9/php \
        php7.1 \
        php7.1-fpm \
        # php libs
        php7.1-apcu \
        php7.1-bcmath \
        php7.1-common \
        php7.1-ctype \
        php7.1-curl \
        php7.1-dom \
        php7.1-fileinfo \
        php7.1-gd \
        php7.1-iconv \
        php7.1-json \
        php7.1-mbstring \
        php7.1-memcached \
        php7.1-mysqli \
        php7.1-opcache \
        php7.1-openssl \
        php7.1-pdo \
        php7.1-pdo_mysql \
        php7.1-pgsql \
        php7.1-pdo_sqlite \
        php7.1-phar \
        php7.1-redis \
        php7.1-session \
        php7.1-simplexml \
        php7.1-sqlite3 \
        php7.1-tokenizer \
        php7.1-xml \
        php7.1-xmlreader \
        php7.1-xmlwriter \
        php7.1-zip \
        php7.1-zlib \
        # Composer
        composer \
        php7.1-composer \
	# Clear apk's cache
	&& apk-cleanup


## Copy scripts
ADD /rootfs /


## Config
RUN \
    ln -s "/etc/php/$PHP_VERSION/" "/etc/php7" \
    && rm -f "/etc/php7/php-fpm.conf" \
    && ln -s "/etc/php/php-fpm.conf" "/etc/php7/php-fpm.conf" \
    # Create default webroot folder
    && mkdir -p /var/www \
    && chown www-data:www-data /var/www


## Expose php-fpm port
EXPOSE 9000
