FROM dsuite/alpine-php:{{DSUITE_VERSION}}


LABEL org.opencontainers.image.title="docker-suite dsuite/alpine-php:{{DSUITE_VERSION}}-fpm image" \
    org.opencontainers.image.created="{{DOCKER_IMAGE_CREATED}}" \
    org.opencontainers.image.revision="{{DOCKER_IMAGE_REVISION}}"


## NGINX Config
ENV NGINX_USER=www-data \
    PHP_FPM_ENABLE=true

